FROM openjdk:17

ARG SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_URL = ${SPRING_DATASOURCE_URL}

ARG SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_USERNAME = ${SPRING_DATASOURCE_USERNAME}

ARG SPRING_DATASOURCE_PASSWORD
ENV SPRING_DATASOURCE_PASSWORD = ${SPRING_DATASOURCE_PASSWORD}

ADD ./instzaa.jar instzaa.jar
ADD ./certs/homologacao-571485-InstzaaHMLv2.p12 /certs/homologacao-571485-InstzaaHMLv2.p12
ENTRYPOINT ["java", "-jar", "instzaa.jar"]
